FROM node:20-alpine

WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY apps/api ./apps/api
COPY packages ./packages
RUN npm install
RUN npm run -w apps/api build

EXPOSE 4000
CMD ["npm", "run", "-w", "apps/api", "start"]
