FROM node:20-alpine

WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY apps/web ./apps/web
RUN npm install
RUN npm run -w apps/web build

EXPOSE 3000
CMD ["npm", "run", "-w", "apps/web", "start"]
